name: Build AppImage

on:
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-22.04

    env:
      APPDIR: AppDir
      APPVERSION: ${{ github.head_ref || github.ref_name }}
      CREATE_APPDIR_TGZ: false

    steps:
    - name: Checkout Code::Blocks
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update

        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          git \
          zip \
          unzip \
          gettext \
          libgtk-3-dev \
          libboost-dev \
          libboost-system-dev \
          libboost-filesystem-dev \
          libzstd-dev \
          wget

    - name: Checkout wxWidgets
      run: |
        git clone --depth=1 --branch v3.3.2 \
          https://github.com/wxWidgets/wxWidgets.git
        cd wxWidgets
        git submodule update --init
        git status

    - name: Build wxWidgets
      run: |
        export WX_PREFIX="${PWD}/${APPDIR}"
        cd wxWidgets

        mkdir buildgtk
        cd buildgtk

        ../configure \
          --prefix=${WX_PREFIX} \
          --disable-shared \
          --disable-sys-libs \
          --with-gtk=3 \
          --enable-secretstore=no

        make -j$(nproc)
        make install

    - name: Bootstrap Code::Blocks
      run: |
        ACLOCAL_FLAGS="-I ${PWD}/${APPDIR}/share/aclocal" ./bootstrap

    - name: Configure Code::Blocks
      run: |
        export PKG_CONFIG_PATH=${APPDIR}/lib/pkgconfig:$PKG_CONFIG_PATH
        ./configure \
          --with-contrib-plugins=all \
          --with-wx-config=${APPDIR}/bin/wx-config \
          --disable-sys-libs --enable-static-wx \
          --prefix=$PWD/$APPDIR

    - name: Build Code::Blocks
      run: |
        make -j$(nproc)

    - name: Install into AppDir
      run: |
        make install

    - name: Download appimagetool
      run: |
        wget -O appimagetool.AppImage \
          https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage

        chmod +x appimagetool.AppImage

    - name: Prepare AppDir
      run: |
        cat > ${APPDIR}/AppRun << 'EOF'
        #!/bin/sh

        HERE="$(dirname "$(readlink -f "${0}")")"
        export PATH="${HERE}/bin:$PATH"
        export LD_LIBRARY_PATH="${HERE}/lib:${HERE}/lib/codeblocks/wxContribItems:$LD_LIBRARY_PATH"
        export CODEBLOCKS_DATA_DIR="${HERE}"
        exec "${HERE}/bin/codeblocks" "$@"
        EOF

        chmod +x ${APPDIR}/AppRun

    - name: Copy desktop file
      run: |
        cp src/mime/codeblocks.desktop ${APPDIR}/

    - name: Copy icon
      run: |
        cp src/mime/codeblocks.png ${APPDIR}/

    - name: Add app name to env
      run: |
        echo "APPNAME=CodeBlocks-${{ env.APPVERSION }}-x86_64.AppImage" >> $GITHUB_ENV
        echo "APPDIR_TGZ=CodeBlocks-${{ env.APPVERSION }}-x86_64.tgz" >> $GITHUB_ENV

    - name: Fix wx-config
      run: |
        rm -f ${APPDIR}/bin/wx-config
        cat > ${APPDIR}/bin/wx-config << 'EOF'
        #!/bin/sh
        ${APPDIR}/lib/wx/config/gtk3-unicode-static-3.3 --prefix=${APPDIR} "$@"
        EOF

        chmod +x ${APPDIR}/bin/wx-config

    - name: Create dev tarball
      if: env.CREATE_APPDIR_TGZ != 'false'
      run: |
        tar -czf ${APPDIR_TGZ} ${APPDIR}

    - name: Cleanup Appdir
      run: |
        rm -rf ${APPDIR}/share/man
        find ${APPDIR}/lib/ -type f -name *.a -exec truncate -s 0 {} +
        rm -f ${APPDIR}/lib/lib*.la
        rm -f ${APPDIR}/lib/codeblocks/plugins/lib*.la
        rm -f ${APPDIR}/lib/codeblocks/wxContribItems/lib*.la


    - name: Checkout libgit2
      run: |
        git clone --depth=1 --branch v1.9.4 \
          https://github.com/libgit2/libgit2.git

    - name: Build libgit2
      run: |
        cd libgit2
        mkdir build-libgit2
        cd build-libgit2
        cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DUSE_HTTPS=OFF -DREGEX_BACKEND=builtin -DUSE_SSH=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
        cmake --build . -j
        sudo cmake --install .

    - name: Checkout cbvcs
      run: |
        git clone --depth=1 https://github.com/josephch/cbvcs

    - name: Build cbvcs
      run: |
        export APPDIR=$PWD/${APPDIR}
        export PKG_CONFIG_PATH=${APPDIR}/lib/pkgconfig
        export PATH=${APPDIR}/bin/:$PATH
        export WXPREFIX=${APPDIR}
        echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
        ls $PKG_CONFIG_PATH
        cd cbvcs
        cmake -B build-cbvcs/ .
        cmake --build build-cbvcs -j

    - name: Install cbvcs to AppDir
      run: |
        cp cbvcs/cbvcs.so ${APPDIR}/lib/codeblocks/plugins/
        cp cbvcs/cbvcs.zip ${APPDIR}/share/codeblocks

    - name: Fetch CbProjectFromCompileCommands
      run: |
        git clone --depth=1 https://github.com/josephch/CbProjectFromCompileCommands
        cd CbProjectFromCompileCommands
        git submodule update --init

    - name: Build CbProjectFromCompileCommands
      run: |
        export APPDIR=$PWD/${APPDIR}
        export PKG_CONFIG_PATH=${APPDIR}/lib/pkgconfig
        export PATH=${APPDIR}/bin/:$PATH
        export WXPREFIX=${APPDIR}
        cd CbProjectFromCompileCommands
        cmake -B build-plugin/ .
        cmake --build build-plugin -j

    - name: Install CbProjectFromCompileCommands to AppDir
      run: |
        cp CbProjectFromCompileCommands/libCbProjectFromCompileCommands.so ${APPDIR}/lib/codeblocks/plugins/CbProjectFromCompileCommands.so
        cp CbProjectFromCompileCommands/CbProjectFromCompileCommands.zip ${APPDIR}/share/codeblocks

    - name: Fetch cb-ClangTidy
      run: |
        git clone --depth=1 https://github.com/josephch/cb-ClangTidy
        cd cb-ClangTidy
        git submodule update --init --recursive

    - name: Build cb-ClangTidy
      run: |
        export APPDIR=$PWD/${APPDIR}
        export PKG_CONFIG_PATH=${APPDIR}/lib/pkgconfig
        export PATH=${APPDIR}/bin/:$PATH
        export WXPREFIX=${APPDIR}
        cd cb-ClangTidy
        cmake -B build-plugin/ .
        cmake --build build-plugin -j

    - name: Install cb-ClangTidy to AppDir
      run: |
        cp cb-ClangTidy/CbClangTidy.so ${APPDIR}/lib/codeblocks/plugins/
        cp cb-ClangTidy/CbClangTidy.zip ${APPDIR}/share/codeblocks

    - name: Fetch ProjectExporter
      run: |
        git clone --depth=1 https://github.com/josephch/CBProjectExporter

    - name: Build ProjectExporter
      run: |
        export APPDIR=$PWD/${APPDIR}
        export PKG_CONFIG_PATH=${APPDIR}/lib/pkgconfig
        export PATH=${APPDIR}/bin/:$PATH
        export WXPREFIX=${APPDIR}
        cd CBProjectExporter
        cmake -B build-plugin/ .
        cmake --build build-plugin -j

    - name: Install ProjectExporter to AppDir
      run: |
        cp CBProjectExporter/bin/ProjectExporter.so ${APPDIR}/lib/codeblocks/plugins/
        cp CBProjectExporter/bin/ProjectExporter.zip ${APPDIR}/share/codeblocks/

    - name: Fetch UnitTestPlugin
      run: |
        git clone --depth=1 https://github.com/josephch/cb-UnitTestPlugin

    - name: Build UnitTestPlugin
      run: |
        export APPDIR=$PWD/${APPDIR}
        export PKG_CONFIG_PATH=${APPDIR}/lib/pkgconfig
        export PATH=${APPDIR}/bin/:$PATH
        export WXPREFIX=${APPDIR}
        cd cb-UnitTestPlugin
        cmake -B build-plugin/ .
        cmake --build build-plugin -j

    - name: Install UnitTestPlugin to AppDir
      run: |
        cp cb-UnitTestPlugin/UnitTest.so ${APPDIR}/lib/codeblocks/plugins/
        cp cb-UnitTestPlugin/UnitTest.zip ${APPDIR}/share/codeblocks/

    - name: Build AppImage
      run: |
        ARCH=x86_64 \
        ./appimagetool.AppImage \
          ${APPDIR} \
          ${APPNAME}

    - name: Upload AppImage
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.APPNAME }}
        path: ${{ env.APPNAME }}
        archive: false

    - name: Upload dev tarball
      if: env.CREATE_APPDIR_TGZ != 'false'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.APPDIR_TGZ }}
        path: ${{ env.APPDIR_TGZ }}
        archive: false

